# Generated by Django 5.0.4 on 2024-04-24 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_historicalcurrency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_rate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalcurrency_rate',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 7, 9, 3, 282932), editable=False),
            preserve_default=False,
        ),
    ]
